name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [12.x]
        machines: [1,2]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
        env:
          CI: true
          SPACE_ID: ${{ secrets.SPACE_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: exe-cypress-test
        uses: cypress-io/github-action@v1
        timeout-minutes: 10
        with:
          record: true
          parallel: true
          group: Parallel 2x on ${{ matrix.os }}
          start: npm run develop
        env:
           CI: true
           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
           SPACE_ID: ${{ secrets.SPACE_ID }}
           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Upload coverage to Codecov
        run: |
          npm install -g codecov
          codecov -t ${{ secrets.CODECOV_TOKEN }}

